### ISSUE TITLE
Web Design

### ISSUE THREAD

**Issue by hcm444** [hcm444/animal-farm#1]
Animal Farm is LIVE!!!!!!! I need a designer to implement a cool common theme across all templates. Please just use CSS and HTML for now, if you are interested in making the website responsive with JavaScript lets negotiate first.
![index](https://github.com/hcm444/animal-farm/assets/32826270/2b9fabae-f396-4d70-a555-f400435d7196)
![welcome](https://github.com/hcm444/animal-farm/assets/32826270/6ac35bae-94c0-4931-82c2-c6ca1af143a9)
![Register](https://github.com/hcm444/animal-farm/assets/32826270/bb76a0af-13d2-4d9e-bf35-5d403bcd49ae)
![login](https://github.com/hcm444/animal-farm/assets/32826270/ad49747b-8c60-49fd-a9c4-b9571e8b810d)

**Comment by AswanthJabba** [comment]
how do I raise PR to contribute, I am not able to add reviewer.
