### ISSUE TITLE
Button Formatting

### ISSUE THREAD

**Issue by hcm444** [hcm444/animal-farm#12]
For the index.html clean up the layout of the buttons.![image](https://github.com/hcm444/animal-farm/assets/32826270/727426c2-5514-4806-aa48-2b0d1da6e08e)

**Comment by DerMoehre** [comment]
Hey, 
I'd like to help with this issue :) 
I am more into Python (or did this more often in the past) but I would like to give it a try :)

**Comment by hcm444** [comment]
Sure go ahead

**Comment by DerMoehre** [comment]
I just tried to start up the server. In the ReadMe is written, that I shoul migrate the database with migration.py but there is no such file in the repository

The server starts but there is no content. Am I doing something wrong?

**Comment by hcm444** [comment]
DerMoehre, It's a flask app. Therefore clone the repo and ensire all requirements are installed. They run python app,py or python3 app.py There will not be content because the database is generated locally. Register with a username and password so you can see local content by auto-hosting on port 5000 or port 8080. This is how we test flask apps locally.

**Comment by DerMoehre** [comment]
Thank you for explanation :)

On startup I get the error ImportError: cannot import name 'EVENT_TYPE_OPENED' from 'watchdog.events' although I installed all the requirements

**Comment by DerMoehre** [comment]
Okay, it worked :) I can finally start the development

What is your goal on this one? Style the links like the post button? Could you give me a slightly deeper explanation? :)

**Comment by hcm444** [comment]
Yeah the post button is fixed, you can try applying a style you like just organized the button format better
