### ISSUE TITLE
Potential Brute Force Vulnerability

### ISSUE THREAD

**Issue by hcm444** [hcm444/animal-farm#14]
Hackers could potentially brute force attack accounts, passwords are encrypted with SHA-256.

**Comment by Pulkitxm** [comment]
Can I get assigned? let me know how to start.

**Comment by AswanthJabba** [comment]
A simple solution would be to add password restrictions for users while registering - such as length to be atleast 10 and must contain atleast one lowercase letter, atleast one uppercase letter, atleast one number and atleast one special character.

![image](https://github.com/hcm444/animal-farm/assets/86704864/a451be55-1fcc-4c63-9466-ae1e83964967)

**Comment by hcm444** [comment]
If you can implement this that would be great! Please look at the defined tables from your local test of the site. Go ahead and check it out if you can solve it I believe in you.

**Comment by hcm444** [comment]
Big thanks to Bchass And AswanthJabba!
