### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by interrrp** [hcm444/animal-farm#17]
why are you storing users' IP addresses?

**Comment by AustXnsheep** [comment]
I was also wondering that.

**Comment by interrrp** [comment]
they should have implemented it by now though

**Comment by hcm444** [comment]
Why store IP addresses? It was to prevent spamming in my original version. Only 1000 posts max are saved in the database so data deletes itself over time. Encrypting IP addresses the same way as user passwords is a good idea.
